FROM node:20.10.0-alpine

WORKDIR /app

RUN npm i lerna -g

RUN mkdir packages

COPY packages/core ./packages/core

COPY package.json lerna.json ./

RUN npm install

RUN /usr/local/bin/npx lerna run buildTest --scope=core --concurrency=2

CMD ["/usr/local/bin/npx", "lerna", "run", "test", "--scope=core"]