FROM node:20.10.0-alpine

WORKDIR /app

RUN npm i lerna -g

RUN mkdir packages

COPY packages/core ./packages/core
COPY packages/http-adapters ./packages/http-adapters

COPY package.json lerna.json ./

RUN npm install

RUN /usr/local/bin/npx lerna run build --scope=core --concurrency=2
RUN /usr/local/bin/npx lerna run buildTest --scope=http-adapters --concurrency=2

CMD ["/usr/local/bin/npx", "lerna", "run", "test", "--scope=http-adapters"]