FROM node:20.10.0-alpine

WORKDIR /app

RUN npm i lerna -g

RUN mkdir packages

COPY packages/core ./packages/core
COPY packages/postgresql-adapters ./packages/postgresql-adapters
COPY packages/devices-notifier-service ./packages/devices-notifier-service

COPY package.json lerna.json ./

RUN npm install

RUN /usr/local/bin/npx lerna run build

CMD ["/usr/local/bin/npx", "lerna", "run", "start", "--scope=devices-notifier-service"]